services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  mongodb-data:
    driver: local
