services:
  backend:
    build: .
    ports:
      - \"3003:3003\"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
      - MONGO_INITDB_DATABASE=${MONGODB_DB_NAME}
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  mongodb-data:
    driver: local
